from collections import defaultdict
import pyomo.environ as pyo
from pyomo.contrib.appsi.solvers import Highs
from network import Network, Route, Edge

def solve_master_problem(network: Network):
    """
    Master problem for the column generation algorithm. This optimization aims to minimize the total traveling distance / cost that satisfies all the 
    edge level demand. Variable x_r is the number of times route r is carried out, with the routes being generated by the subproblem.

    Parameters:
    - network: Network object containing nodes, edges, and routes

    Returns:
    - result: Highs solver result object
    """

    
    model = pyo.ConcreteModel("master_problem")
    model.x = pyo.Var(network.routes, within=pyo.NonNegativeReals)
    model.obj = pyo.Objective(expr=sum(r.distance * model.x[r] for r in network.routes))
    
    # Print model components for debugging
    # print("Routes in network:", len(network.routes))
    # print("Edges in network:", len(network.edges))

    # print('Routes:')
    # for route in network.routes:
    #     print(route)

    def demand_constraint_rule(model, e):

        return sum(model.x[r] for r in network.edges[e].routes) >= network.edges[e].demand if network.edges[e].demand > 0 else pyo.Constraint.Skip
    
    model.flow_cons = pyo.Constraint(network.edges, rule=demand_constraint_rule)

    # print the full model
    # print('Full model:')
    # model.pprint()

    solver = Highs()
    result = solver.solve(model)

    optimal_value = pyo.value(model.obj)

     # Store optimization results in dictionary
    optimal_routes = {r: model.x[r].value for r in network.routes if model.x[r].value > 1e-6}


    # Print optimization results
    # print("\nOptimization Results:")
    # for r in network.routes:
    #     if model.x[r].value > 1e-6:  # Only print non-zero values (accounting for numerical precision)
    #         print(f"Route {r}: {model.x[r].value:.2f}")
    
    
    # dual_values = {}
    # for e in network.edges:
    #     if network.edges[e].demand > 0:  # Only print for edges with demand
    #         # Get dual value from the solver's result
    #         constraint_dual = solver.get_duals([model.flow_cons[e]])
    #         dual_values[e] = constraint_dual[model.flow_cons[e]]
    #     else:
    #         dual_values[e] = 0
    for e in network.edges:
        if network.edges[e].demand > 0:
            network.edges[e].dual_value = solver.get_duals([model.flow_cons[e]])[model.flow_cons[e]]
    
    return optimal_value, optimal_routes



def find_integer_solution(network: Network):
    """
    Integer version of the master problem for the column generation algorithm. This optimization aims to minimize 
    the total traveling distance / cost that satisfies all the edge level demand. Variable x_r is the integer 
    number of times route r is carried out.

    Parameters:
    - network: Network object containing nodes, edges, and routes

    Returns:
    - result: Highs solver result object
    """
    
    model = pyo.ConcreteModel("integer_master_problem")
    model.x = pyo.Var(network.routes, within=pyo.NonNegativeIntegers)
    model.obj = pyo.Objective(expr=sum(r.distance * model.x[r] for r in network.routes))
    
    def demand_constraint_rule(model, e):
        return sum(model.x[r] for r in network.edges[e].routes) >= network.edges[e].demand if network.edges[e].demand > 0 else pyo.Constraint.Skip
    
    model.flow_cons = pyo.Constraint(network.edges, rule=demand_constraint_rule)

    solver = Highs()
    result = solver.solve(model)

    optimal_value = pyo.value(model.obj)
    optimal_routes = {r: model.x[r].value for r in network.routes if model.x[r].value > 1e-6}
        
    return optimal_value, optimal_routes



def solve_subproblem(network: Network):
    """
    Finds the shortest cycle starting and ending at dc_0 using a modified Bellman-Ford algorithm
    with 2D matrices to track distances and predecessors at each step.
    """
    import math
    
    # Start from first DC (dc_0)
    start_dc = next(iter(network.dcs.values())).name
    
    # Get number of nodes and max steps
    n_nodes = len(network.nodes)
    max_steps = 10  # Maximum steps allowed in path
    
    # Create node to index mapping for matrix operations
    node_to_idx = {node.name: idx for idx, node in enumerate(network.nodes.values())}
    idx_to_node = {v: k for k, v in node_to_idx.items()}
    
    # Initialize 2D matrices for distances and predecessors
    distances = [[0] * (max_steps + 1) for _ in range(n_nodes)]
    reduced_costs = [[math.inf] * (max_steps + 1) for _ in range(n_nodes)]
    predecessors = [[None] * (max_steps + 1) for _ in range(n_nodes)]
    
    # Set initial distance for start_dc
    start_idx = node_to_idx[start_dc]
    reduced_costs[start_idx][0] = 0
    
    # Update reduced_cost, distances, predecessors step by step
    for t in range(max_steps):
        
        for u_idx in range(n_nodes):
            u = idx_to_node[u_idx]
            for e in network.nodes[u].outgoing_edges:
                v = e.destination
                v_idx = node_to_idx[v.name]
                reduced_cost = e.distance - e.dual_value 

                if reduced_costs[u_idx][t] + reduced_cost < reduced_costs[v_idx][t+1]:
                    reduced_costs[v_idx][t+1] = reduced_costs[u_idx][t] + reduced_cost
                    distances[v_idx][t+1] = distances[u_idx][t] + e.distance 
                    predecessors[v_idx][t+1] = u_idx
                # else:
                #     reduced_costs[v_idx][t+1] = reduced_costs[v_idx][t]
                #     distances[v_idx][t+1] = distances[v_idx][t]
                #     predecessors[v_idx][t+1] = v_idx

    # Find best cycle back to start_dc
    path = [start_dc]
    curr_idx = start_idx
    # check if there is a negative reduced cost cycle
    if reduced_costs[start_idx][max_steps] < -1e-6:
        # construct the cycle using predecessors
        for t in range(max_steps, 0, -1):
            curr_idx = predecessors[curr_idx][t]
            if idx_to_node[curr_idx] != path[-1]:
                path.append(idx_to_node[curr_idx])
        
        if path[0] == path[-1]:
            path.reverse()
            r = Route([network.nodes[n] for n in path])
            return r
    
    return None


'''
def solve_subproblem(network: Network):

    print("Solving subproblem")
    model = pyo.ConcreteModel("subproblem")
    model.x = pyo.Var(network.edges, within=pyo.Binary)

    # Print the actual indices in model.x
    print("\nPrinting coefficients:")
    for e in network.edges:
        print(f"Edge {e}: {network.edges[e].distance - network.edges[e].dual_value}")

    # minimize reduced cost
    model.obj = pyo.Objective(expr=sum((network.edges[e].distance - network.edges[e].dual_value) * model.x[e] for e in network.edges))
   
    # add constraints
    def flow_balance_constraint_rule(model, i):
        return sum(model.x[e.name] for e in network.nodes[i].incoming_edges) - sum(model.x[e.name] for e in network.nodes[i].outgoing_edges) == 0
    model.flow_balance_cons = pyo.Constraint(network.nodes, rule=flow_balance_constraint_rule)

    # # rounte must start and end at a dc
    def driver_start_end_constraint_rule(model, i):
        return sum(sum(model.x[e.name] for e in network.nodes[i].outgoing_edges) for i in network.dcs) >= 1
    model.driver_start_end_cons = pyo.Constraint(rule=driver_start_end_constraint_rule)

    # maximum distance constraint
    def max_distance_constraint_rule(model, e):
        return sum(network.edges[e].distance * model.x[e] for e in network.edges) <= 10000
    model.max_distance_cons = pyo.Constraint(rule=max_distance_constraint_rule)

    # maximum number of segments constraint
    def max_segments_constraint_rule(model, e):
        return sum(model.x[e] for e in network.edges) <= 10
    model.max_segments_cons = pyo.Constraint(rule=max_segments_constraint_rule)


    solver = Highs()
    result = solver.solve(model)

    for e in network.edges:
        if pyo.value(model.x[e]) > 0:
            print(f"Edge {e}: {pyo.value(model.x[e]):.2f}")
    
    print(result)

    # Convert edges to route
    active_edges = [(e, pyo.value(model.x[e])) for e in network.edges if pyo.value(model.x[e]) > 0]
    
    # Print original edge format
    print("\nActive edges:")
    for e, val in active_edges:
        print(f"Edge {e}: {val:.2f}")
    
    return result
    
'''